openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /names/:
    get:
      operationId: names_list
      description: |-
        Return a list of all name groups with a list of containing name entities.

        DEV NOTES:
        According to the task directly - there are two endpoints requested, one for NameGroup creation only for
        authenticated users, and one for displaying list of NameGroup objects, authentication not mentioned. Possibly
        it would be good that other views are available for admins just in case.
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - names
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedNameGroupList'
          description: ''
    post:
      operationId: names_create
      description: |-
        Return a list of all name groups with a list of containing name entities.

        DEV NOTES:
        According to the task directly - there are two endpoints requested, one for NameGroup creation only for
        authenticated users, and one for displaying list of NameGroup objects, authentication not mentioned. Possibly
        it would be good that other views are available for admins just in case.
      tags:
      - names
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NameGroup'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NameGroup'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/NameGroup'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NameGroup'
          description: ''
  /names/{id}/:
    get:
      operationId: names_retrieve
      description: |-
        Return a list of all name groups with a list of containing name entities.

        DEV NOTES:
        According to the task directly - there are two endpoints requested, one for NameGroup creation only for
        authenticated users, and one for displaying list of NameGroup objects, authentication not mentioned. Possibly
        it would be good that other views are available for admins just in case.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this name group.
        required: true
      tags:
      - names
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NameGroup'
          description: ''
    put:
      operationId: names_update
      description: |-
        Return a list of all name groups with a list of containing name entities.

        DEV NOTES:
        According to the task directly - there are two endpoints requested, one for NameGroup creation only for
        authenticated users, and one for displaying list of NameGroup objects, authentication not mentioned. Possibly
        it would be good that other views are available for admins just in case.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this name group.
        required: true
      tags:
      - names
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NameGroup'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NameGroup'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/NameGroup'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NameGroup'
          description: ''
    patch:
      operationId: names_partial_update
      description: |-
        Return a list of all name groups with a list of containing name entities.

        DEV NOTES:
        According to the task directly - there are two endpoints requested, one for NameGroup creation only for
        authenticated users, and one for displaying list of NameGroup objects, authentication not mentioned. Possibly
        it would be good that other views are available for admins just in case.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this name group.
        required: true
      tags:
      - names
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedNameGroup'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedNameGroup'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedNameGroup'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NameGroup'
          description: ''
    delete:
      operationId: names_destroy
      description: |-
        Return a list of all name groups with a list of containing name entities.

        DEV NOTES:
        According to the task directly - there are two endpoints requested, one for NameGroup creation only for
        authenticated users, and one for displaying list of NameGroup objects, authentication not mentioned. Possibly
        it would be good that other views are available for admins just in case.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this name group.
        required: true
      tags:
      - names
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /names/{id}/move/:
    put:
      operationId: names_move_update
      description: |-
        "Move" entity to another name group.

        De facto update name group for entity specified in URL.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - names
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NameEntity'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NameEntity'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/NameEntity'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NameEntity'
          description: ''
components:
  schemas:
    NameEntity:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        name_group:
          type: integer
      required:
      - id
      - name
      - name_group
    NameGroup:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        entities:
          type: array
          items:
            type: string
          readOnly: true
      required:
      - entities
      - id
      - name
    PaginatedNameGroupList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/NameGroup'
    PatchedNameGroup:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        entities:
          type: array
          items:
            type: string
          readOnly: true
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
